/* V2 secondary screens: shared state and original UE identifiers retained. */
screens.splice(2,0,['Connection & recovery',[['connect','02b-1','Pairing result'],['signal','04a-1','Signal check'],['partial','10b','Session saved']]]);
Object.assign(S,{contactIssue:false,pairFailed:false,limited:false,connectFrom:'task'});
const originalGo=go;
go=function(to){if(S.screen==='complete'&&to!=='report')S.limited=false;originalGo(to)};
const oldMain=main,oldOnboarding=onboarding,oldComplete=complete,oldBegin=begin,oldReport=report;
const sectionHead=(title,copy)=>`<div class="flow-heading"><h1>${title}</h1><p class="lead">${copy}</p></div>`;
const progressHint=n=>`<div class="setup-progress" aria-label="Setup step ${n} of 3">${['Your details','Your choices','Your device'].map((t,i)=>`<span class="${i+1===n?'current':i+1<n?'done':''}"><i>${i+1<n?'✓':i+1}</i>${t}</span>`).join('')}</div>`;
const saveRow=(title,detail,ok=true)=>`<div class="save-row"><span class="save-icon ${ok?'':'pending'}">${icon(ok?'check':'info')}</span><div><h3>${title}</h3><p>${detail}</p></div></div>`;
begin=function(intent,reuse=false){S.connectFrom='task';S.limited=false;oldBegin(intent,reuse)};
wear=function(){return `${sectionHead('Make yourself comfortable.','A steady fit is the first step to a useful check.')}<div class="hardware-hero"><img src="assets/product-render-20260918.png" alt="Brainlume headset with forehead band and earcups"><span>YOUR BRAINLUME</span></div><div class="fit-instructions">${[['Forehead contact','Place the band against your skin. Move hair away from the contact area.'],['A comfortable fit','Adjust both earcups evenly. Secure should never feel tight.'],['A quiet moment','Sit naturally, relax your jaw and keep your head still.']].map(([t,d],i)=>`<div class="fit-step"><b>0${i+1}</b><div><h2>${t}</h2><p>${d}</p></div></div>`).join('')}</div><div class="destination-note">${icon(S.intent==='recovery'?'sun':'scan')}<span>Next: ${S.intent==='recovery'?'Before measurement':'Check my state'} · 3 min</span></div><div class="bottom-action">${btn('Check my fit','wear-ready')}</div>`};
function signalCheck(){return `${sectionHead(S.contactIssue?'A small adjustment.':'You’re ready to begin.',S.contactIssue?'Move hair away from your forehead and adjust the band gently.':'All three channels are ready. Keep this comfortable position.')}<div class="signal-orbit ${S.contactIssue?'needs-contact':''}">${icon(S.contactIssue?'info':'check')}<span>${S.contactIssue?'Adjust contact':'Good contact'}</span></div><section class="channel-checks">${[1,2,3].map(c=>`<div><span>CH${c}</span><i class="contact-bars ${S.contactIssue&&c===2?'weak':''}"><b></b><b></b><b></b><b></b></i><strong>${S.contactIssue&&c===2?'Adjust':'Ready'}</strong></div>`).join('')}</section><p class="footnote text-center">${S.contactIssue?'Check the fit, then try the contact check again.':'Contact preview · No live device data'}</p><div class="destination-note">${icon('clock')}<span>${S.intent==='recovery'?'Before → Light Session → After':'State check → Your result'}</span></div><div class="bottom-action">${btn(S.contactIssue?'Check contact again':S.intent==='recovery'?'Start Before measurement':'Start my check',S.contactIssue?'check-contact-again':'begin-recording')}${goBtn('Review wearing guide','wear','text-btn')}</div>`}
function pairingResult(){return `${sectionHead(S.pairFailed?'Let’s try connecting again.':'Your Brainlume is nearby.',S.pairFailed?'Keep the headset close and make sure it is switched on.':'Confirm the device below to continue.')}<div class="hardware-hero"><img src="assets/product-render-20260918.png" alt="Brainlume headset"></div><section class="connection-card"><div class="flex between"><div class="flex">${icon('device')}<h2>Brainlume 2.0</h2></div><span class="pill ${S.pairFailed?'':'good'}">${S.pairFailed?'Not connected':'Available'}</span></div><p>${S.pairFailed?'Connection could not be completed. Your task has not started.':'Demo device · Nearby'}</p></section>${S.pairFailed?'<div class="banner warning">Check Bluetooth in your phone’s settings and try again.</div>':''}<div class="bottom-action">${btn(S.pairFailed?'Try again':'Connect and continue',S.pairFailed?'retry-pair':'pair')}${goBtn('Back','activate','text-btn')}</div><p class="footnote text-center">Connection is simulated in this design preview.</p>`}
selfReport=function(){return `${sectionHead('How do you feel?','A quick check-in with yourself. There’s no right or wrong answer.')}<div class="self-symbol">${icon(S.self==='Relaxed'?'smile':S.self==='Tense'?'tense':'neutral')}</div><div class="feeling-list">${[['Tense','tense','A little wound up'],['Not sure','neutral','Somewhere in between'],['Relaxed','smile','At ease right now']].map(([t,i,d])=>`<button class="feeling-choice ${S.self===t?'selected':''}" data-action="self" data-value="${t}" aria-pressed="${S.self===t}">${icon(i)}<span><strong>${t}</strong><small>${d}</small></span><i>${S.self===t?icon('check'):''}</i></button>`).join('')}</div><p class="footnote text-center mt">Your answer adds context to the sensor reading.</p><div class="bottom-action">${goBtn('See my result','result')}${btn('Skip for now','skip-self','text-btn')}</div>`};
device=function(){return `${sectionHead('Your Brainlume.',S.device?'Connected and ready when you are.':'Connect your device for your next check.')}<div class="hardware-hero compact"><img src="assets/product-render-20260918.png" alt="Brainlume 2.0 headset"></div><div class="device-overview"><div><span>Connection</span><strong class="${S.device?'green':'amber'}">${S.device?'Connected':'Offline'}</strong></div><div><span>Battery</span><strong>${S.device?'90%':'—'}</strong></div></div>${S.device?`<div class="health-list">${saveRow('EEG contact','Check contact before each measurement')}${saveRow('Light system','Ready · Temperature normal')}${saveRow('Firmware','Version 2.0.14 · Demo status')}</div><div class="bottom-action">${btn('Review device fit','fit','secondary')}</div>`:`<div class="bottom-action">${btn('Connect my device','settings-connect')}</div>`}<div class="section-heading"><h2>Make it yours</h2></div><div class="settings-menu">${[['settings','Personal calibration','Your details and sensor conditions','profile'],['shield','Data & privacy','Choose how your data is used','privacy'],['info','Firmware information','Device software and status','firmware'],['download','Device diagnostics','Download a sample device log','diagnostics']].map(([i,t,d,to])=>`<button class="settings-row" data-action="${['firmware','diagnostics'].includes(to)?to:'go'}" data-to="${to}">${icon(i)}<span><strong>${t}</strong><small>${d}</small></span>${icon('arrow')}</button>`).join('')}</div><p class="footnote mt">All connection and device readings are simulated.</p>`};
complete=function(){if(S.limited)return limitedSummary();if(S.history&&S.historyIndex>0)return oldComplete();return `${sectionHead(S.history?'Your saved session.':'A pause, well taken.','A view of your state before and after this session.')}<div class="session-meta"><span>${S.history?'Today · 09:56 AM':'Just completed'}</span><span>Light Session · 4 min</span></div><section class="result-pair"><div><span>Before</span><strong>38</strong><small>Tense</small></div><i>${icon('arrow')}</i><div><span>After</span><strong>76</strong><small>Relaxed</small></div></section><p class="footnote text-center">Recovery Score · Same 0–100 scale</p><div class="quality-line">${icon('check')}<div><strong>Ready to compare</strong><span>Before and After have sufficient usable data.</span></div></div><div class="section-heading"><h2>What changed</h2><span class="tiny muted">Six dimensions</span></div><div class="extended-comparison">${comparison()}</div><p class="footnote mt">Changes describe this session. They do not establish what caused the change.</p><div class="bottom-action">${goBtn('View detailed report','report')}${goBtn(S.history?'Back to trends':'Back to home',S.history?'trends':'home','secondary')}</div>`};
function limitedSummary(){return `${sectionHead('Some context is missing.','Your session is saved, but these readings are not reliably comparable.')}<div class="quality-line caution">${icon('info')}<div><strong>Limited comparability</strong><span>Different signal conditions between Before and After.</span></div></div><div class="health-list">${saveRow('Before measurement','Saved · Sufficient usable data')}${saveRow('Light Session','Completed · 4 minutes')}${saveRow('After measurement','Saved · Different contact conditions',false)}</div><div class="banner">No numerical change or directional conclusion is shown.</div><p class="lead mt">For a clearer comparison next time, keep the same fit and position throughout the session.</p><div class="bottom-action">${goBtn('Back to trends','trends')}${btn('Start a new session','start-recovery','secondary')}</div>`}
failure=function(){return `${sectionHead('Not enough data to compare.','The After check did not collect enough usable signal.')}<div class="signal-orbit needs-contact">${icon('info')}<span>Result unavailable</span></div><div class="health-list">${saveRow('Before measurement','Saved · Usable signal')}${saveRow('Light Session','Completed')}${saveRow('After measurement','Insufficient data',false)}</div><div class="banner warning">No before-and-after conclusion is shown. Your completed stages stay saved.</div><p class="footnote mt">A new recovery session begins with a fresh Before check.</p><div class="bottom-action">${btn('Start a new recovery session','start-recovery')}${goBtn('Back to home','home','secondary')}</div>`};
function partialSession(){return `${sectionHead('Your session ended safely.','Light and sound are off. You can return whenever you’re ready.')}<div class="signal-orbit">${icon('shield')}<span>Safely ended</span></div><div class="health-list">${saveRow('Before measurement',S.endedStage==='before'||S.endedStage==='measure'?'Incomplete · No result saved':'Saved',!['before','measure'].includes(S.endedStage))}${saveRow('Full comparison','Not available for an incomplete session',false)}</div><p class="footnote mt">Completed measurements remain available for this preview. No missing stage is filled with an estimated value.</p><div class="bottom-action">${goBtn('Back to home','home')}${btn('Start a new session','start-recovery','secondary')}</div>`}
onboarding=function(){if(S.screen==='activate')return `${sectionHead('Meet your Brainlume.','Switch it on and keep it close to your phone.')}<div class="hardware-hero"><img src="assets/product-render-20260918.png" alt="Brainlume headset"></div><div class="fit-instructions">${[['Power on','Check that your headset is switched on.'],['Keep it nearby','Stay close while connecting.'],['Continue your task',S.onboarding?'Finish setup and go to Home.':S.connectFrom==='device'?'Return to Settings once connected.':'Your check will continue after a quick fit check.']].map(([t,d],i)=>`<div class="fit-step"><b>0${i+1}</b><div><h2>${t}</h2><p>${d}</p></div></div>`).join('')}</div><div class="bottom-action">${goBtn('Find my device','connect')}</div><p class="footnote text-center">Device discovery is simulated.</p>`;return `<section class="onboarding-view">${oldOnboarding()}</section>`};
const oldPrivacy=privacy,oldProfile=profile;
privacy=function(){return `${S.onboarding?progressHint(2):''}<section class="preference-view">${oldPrivacy().replace('Device settings','Settings')}</section>`};
profile=function(){return `${S.onboarding?progressHint(1):''}<section class="profile-view">${oldProfile().replace('Save and continue',S.onboarding?'Save and continue':'Save details')}</section>`};
report=function(){return `<section class="report-view">${oldReport().replace('PROFESSIONAL REPORT','SESSION DETAILS')}</section>`};
main=function(){if(S.screen==='signal')return signalCheck();if(S.screen==='connect')return pairingResult();if(S.screen==='partial')return partialSession();return oldMain()};
document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(!el)return;const a=el.dataset.action;if(['begin-recording','check-contact-again','retry-pair','settings-connect','confirm-end'].includes(a)){e.stopImmediatePropagation();if(a==='begin-recording'){S.elapsed=0;go(S.intent==='recovery'?'before':'measure')}if(a==='check-contact-again'){S.contactIssue=false;render(true)}if(a==='retry-pair'){S.pairFailed=false;render(true)}if(a==='settings-connect'){S.connectFrom='device';S.onboarding=false;go('activate')}if(a==='confirm-end'){S.endedStage=S.screen;S.elapsed=0;go('partial')}}},true);
const stateQuery=new URLSearchParams(location.search),extraScreen=stateQuery.get('screen'),variant=stateQuery.get('state');
if(['connect','signal','partial'].includes(extraScreen))S.screen=extraScreen;
if(variant==='poor-contact')S.contactIssue=true;
if(variant==='pair-failed')S.pairFailed=true;
if(variant==='paused'){S.paused=true;S.elapsed=72}
if(variant==='disconnected'){S.disconnected=true;S.elapsed=72}
if(variant==='limited')S.limited=true;
if(variant==='empty')S.empty=true;
if(variant==='offline')S.device=false;
if(variant==='history'){S.history=true;S.historyIndex=0}
if(variant==='summary-only'){S.history=true;S.historyIndex=1}
if(variant==='end'){S.elapsed=72;S.paused=true;S.modal='end'}
render();
