/* V2 visual layer. Shared flows and demo behavior remain in app.js. */
function blueRing(value){return `<div class="ring blue-ring" role="img" aria-label="Recovery Score ${value} out of 100"><svg viewBox="0 0 100 100" aria-hidden="true"><defs><linearGradient id="scoreGradient" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#a9d8f2"/><stop offset="1" stop-color="#9690ef"/></linearGradient></defs><circle class="ring-track" cx="50" cy="50" r="45"/><circle class="blue-fill" cx="50" cy="50" r="45" stroke="url(#scoreGradient)" stroke-dasharray="${value*2.83} 283"/></svg><div><div class="number">${value}</div><small>/ 100</small><span class="ring-label">Recovery Score</span></div></div>`}

function home(){return `<div class="home-intro"><h1>A moment for your mind.</h1><button class="home-connection" data-action="go" data-to="device"><i class="dot"></i>Brainlume ${S.device?'is connected':'is not connected'} ${icon('arrow')}</button></div><div class="round-tasks"><div class="round-task"><button class="circle-action" data-action="start-check" aria-label="Check my state · 3 minutes · State snapshot"><span>Check<br>my state</span></button><strong>3 min</strong><p>State snapshot</p></div><div class="round-task"><button class="circle-action recovery-circle" data-action="start-recovery" aria-label="Start recovery · 9 to 11 minutes · Before and after"><span>Start<br>recovery</span></button><strong>9–11 min</strong><p>Before + after</p></div></div><button class="guide-link" data-action="go" data-to="wear">${icon('info')}<span>Wearing guide</span>${icon('arrow')}</button><section class="recent-open"><div class="section-heading"><h2>Recent check</h2><span class="tiny muted">Today · 09:41</span></div><button class="open-result" data-action="go" data-to="result" aria-label="View recent result: Recovery Score 38, Relaxation Level Tense"><span><small>Recovery Score</small><strong>38<em> / 100</em></strong></span><span><small>Relaxation Level</small><strong class="state-word">Tense</strong></span>${icon('arrow')}</button></section><section class="scenario-section"><div class="section-heading"><h2>Common scenarios</h2><span class="tiny muted">Optional</span></div><div class="context-chips">${['Screen time','Deep work','Meetings','Commute','Bedtime'].map(x=>`<button class="chip ${S.scenario===x?'selected':''}" data-action="scenario" data-value="${x}" aria-pressed="${S.scenario===x}">${x}</button>`).join('')}</div></section>`}

function analysisOverview(){
 const values=[['Focus',55,'Higher indicates more focus.'],['Relaxation',30,'Higher indicates more relaxation.'],['Alertness',66,'Higher indicates more alertness, not necessarily a better state.']];
 const point=(i,v)=>{const a=(-90+i*120)*Math.PI/180;return [160+96*v/100*Math.cos(a),132+96*v/100*Math.sin(a)]};
 const polygon=v=>values.map((_,i)=>point(i,v).join(',')).join(' ');
 return `<section class="analysis-overview" aria-label="State analysis overview"><div class="section-heading"><h2>State overview</h2><span class="analysis-demo">Illustrative data</span></div><p class="analysis-caption">Three signals. A little more context.</p><svg class="state-radar" viewBox="0 0 320 246" role="img" aria-label="Focus 55, Relaxation 30, Alertness 66 on a shared zero to one hundred scale. Brain age is not assessed.">${[25,50,75,100].map(v=>`<polygon points="${polygon(v)}" class="radar-grid"/>`).join('')}${values.map((_,i)=>`<path d="M160 132 L${point(i,100).join(' ')}" class="radar-axis"/>`).join('')}<polygon points="${values.map((v,i)=>point(i,v[1]).join(',')).join(' ')}" class="radar-area"/>${values.map((v,i)=>`<circle cx="${point(i,v[1])[0]}" cy="${point(i,v[1])[1]}" r="4" class="radar-dot"/>`).join('')}<text x="160" y="15" text-anchor="middle">Focus</text><text x="265" y="204" text-anchor="middle">Relaxation</text><text x="55" y="204" text-anchor="middle">Alertness</text><text x="160" y="235" text-anchor="middle" class="radar-scale">Shared scale · 0–100</text></svg><div class="analysis-grid">${values.map(([n,v,d])=>`<div class="analysis-stat"><h3>${n}</h3><p class="analysis-number">${v}<span> / 100</span></p><p class="analysis-direction">${d}</p></div>`).join('')}<div class="analysis-stat brain-age"><h3>Brain age</h3><p class="analysis-number">—<span> years</span></p><p class="analysis-direction">Not assessed</p></div></div><p class="analysis-note">Brain age uses a separate unit and is not included in the radar.</p><details class="disclosure"><summary>How to read these dimensions</summary><p>These are illustrative design values, not measured results. Focus, relaxation and alertness share a 0–100 display scale; they are not percentages. A larger shape does not mean better overall health.</p><p>Brain age is a proposed dimension. Its calculation and supporting evidence have not been defined, so no age estimate is shown.</p></details></section>`;
}

function result(){return `<div class="result-title text-center"><h1>A moment to recharge.</h1></div><div class="score-hero">${blueRing(38)}</div><p class="score-context">Below your recent recovery baseline.</p><div class="relax-inline">Relaxation Level <span>·</span> <strong>Tense</strong></div><div class="recommendation text-center"><h2>A short pause may help.</h2><p class="lead">Low recovery reserve and a tense state.<br>Try a guided reset, if it feels right.</p></div><div class="bottom-action result-action">${btn(`Start recovery · 6–7 min ${icon('arrow')}`,'reuse')}<p class="footnote text-center">This check becomes your Before measurement.</p></div>${analysisOverview()}<div class="banner">Your self-report: <strong>${S.self||'Not provided'}</strong><br>How you feel adds context to the sensor reading.</div><details class="disclosure"><summary>About this score & the evidence</summary><p>Recovery Score is a Brainlume product metric relative to your recent baseline, not a standard clinical measure. All values shown here are illustrative. Metric definitions, baseline rules and physiological interpretation need validation before release.</p><p>EEG estimates have limitations. Use these estimates alongside your own experience, not as a diagnosis.</p></details>`}

function session(){const single=S.screen==='measure',light=S.screen==='light',after=S.screen==='after',blocked=S.bad||S.disconnected;return `<div class="session blue-session ${light?'light':''} ${S.paused||blocked?'paused':''} ${blocked||S.reused&&light?'has-alert':''}">${single?'<div class="measure-top">State check · About 3 minutes</div>':steps()}${S.reused&&light?'<div class="banner reuse-note">Your recent check is saved as <strong>Before</strong>. No need to measure again.</div>':''}${S.disconnected?'<div class="banner warning">Connection lost. Completed stages are saved. Reconnect to continue this stage.</div>':S.bad?'<div class="banner warning">Adjust the forehead contact and stay still. The timer is paused until the signal improves.</div>':''}<div class="session-disc-wrap"><div class="session-disc ${light?'with-light':''}"><div class="disc-halo" aria-hidden="true"></div><div class="disc-clock"><div class="timer" id="timer">${time(S.elapsed)}</div><div class="timer-label">${S.paused?'Paused':blocked?'Waiting for signal':'Active stage time'}</div></div></div></div><div class="session-copy"><h1>${light?'Settle in. Let your eyes rest.':after?'Let’s see where you are.':'Start with where you are.'}</h1><p class="lead">${light?'A gentle pause with light + sound.':'Sit naturally and stay still.'}</p></div><div class="signal">${icon(S.disconnected||S.bad?'info':'check')}${S.disconnected?'Device disconnected':S.bad?'Signal needs attention':light?(S.paused?'Light + sound paused':'Light + sound active'):'Good contact · Signal is stable'}</div>${!light?`<div class="timer-label" id="valid">Valid signal collected: ${time(S.elapsed)}</div>`:`<p class="stage-duration">Light + sound · About 4 min</p>`}<div class="session-actions">${S.disconnected?btn('Reconnect','reconnect','secondary'):S.bad?btn('Check contact','good-signal','secondary'):btn(`${icon(S.paused?'play':'pause')} ${S.paused?'Resume':'Pause'}`,'pause','secondary')}${btn('End session','end','secondary')}</div></div>`}

function trends(){let range=S.range;return `<div class="trend-heading"><h1>Your patterns, over time.</h1></div><div class="segmented" role="group" aria-label="Time range">${[7,30].map(x=>`<button class="${range===x?'active':''}" data-action="range" data-value="${x}" aria-pressed="${range===x}">${x} days</button>`).join('')}</div><p class="range-caption">${range===7?'This week':'Last 30 days'}</p>${S.empty?`<div class="empty">${icon('chart')}<h2>Your story starts here.</h2><p>Complete a recovery session and add a self-report to see patterns over time.</p><div class="bottom-action">${btn('Start your first session','start-recovery')}</div></div>`:`<section class="trend-section"><h2>How you felt after recovery</h2><p class="footnote">Your self-reports · ${range===7?'5':'18'} sessions</p><svg class="chart" viewBox="0 0 320 197" role="img" aria-label="Self-reported relaxation over ${range} days, ranging from tense to relaxed"><text x="0" y="32">Relaxed</text><text x="0" y="91">Neutral</text><text x="0" y="150">Tense</text>${[29,88,147].map(y=>`<path class="grid" d="M65 ${y}H313"/>`).join('')}${[68,129,190,251,311].map(x=>`<path class="grid" d="M${x} 20V158"/>`).join('')}<path class="line" d="${range===7?'M68 143 129 105 190 114 251 63 311 32':'M68 137 98 121 129 138 159 93 190 108 221 59 251 76 281 50 311 32'}"/>${(range===7?[[68,143],[129,105],[190,114],[251,63],[311,32]]:[[68,137],[98,121],[129,138],[159,93],[190,108],[221,59],[251,76],[281,50],[311,32]]).map(([x,y])=>`<circle cx="${x}" cy="${y}" r="3.8"/>`).join('')}${(range===7?['Sat','Mon','Wed','Thu','Fri']:['Aug 13','20','27','Sep 3','11']).map((x,i)=>`<text x="${68+i*61}" y="184" text-anchor="middle">${x}</text>`).join('')}</svg><p class="trend-caption">Feelings you reported, not an overall brain-health score.</p></section><div class="stat-pair"><div><strong>${range===7?'5':'18'}</strong><small>Recovery sessions</small></div><div><strong>${range===7?'51':'184'} <span class="tiny muted">min</span></strong><small>Time for yourself</small></div></div><section class="open-history"><div class="section-heading"><h2>Recent sessions</h2></div>${history.map(([d,t,m],i)=>`<button class="history-row" data-action="history" data-value="${i}"><span class="grow"><strong>${d}</strong><small>${t}</small></span><span class="mood ${i<2?'good':i===2?'neutral':'tense'}"><i></i>${m}</span>${icon('arrow')}</button>`).join('')}</section>`}`}

// Guard the preview-only wearing guide from inheriting a previous task intent.
document.addEventListener('click',e=>{if(e.target.closest('.guide-link'))S.intent='check'},true);
render();
